### ISSUE TITLE
Nitain extract

### ISSUE THREAD

**Issue by larousse96** [WFCD/warframe-discord-emoji#4]
Hi,

This isn't an issue, but i saw that there was no nitan extract in you library... so I made it.
Tested and aprooved in discord ^^

Would be nice to add it, fot other people's sake ^^

See ya

Larousse96
![nitain extract](https://user-images.githubusercontent.com/22483186/37615961-ca126f72-2bae-11e8-9a0f-faae6c207d4e.png)

**Comment by TobiTenno** [comment]
you could add it....

**Comment by DJNeonNight** [comment]
Already added here: #9 
@TobiTenno you can mark this as solved.
